### ISSUE TITLE
Scorch tcpdump unable to collect on multiple interfaces on the same VM

### ISSUE THREAD

**Issue by nblair2** [sandialabs/sceptre-phenix-apps#35]
Due to all tcpdump scorch components being written to the same place (`/dump.pcap`), only one interface from each VM can be collected on.

example:
```
      - name: tcpdump-eth0
        type: tcpdump
        metadata:
          convertToJSON: false
          vms:
          - hostname: host
            iface: eth0
      - name: tcpdump-eth1
        type: tcpdump
        metadata:
          convertToJSON: false
          vms:
          - hostname: host
            iface: eth1
```

Will not work becuase `tcpdump-eth1` and `tcpdump-eth0` both try to write to `/dump.pcap`.
